#!/bin/sh
set -euo pipefail

# Handler format: <cobol program id>.<dummy>
#
# The script file <cobol program id>  must be located at the root of your
# function's deployment package, alongside this bootstrap executable.

while true
do
    # Request the next event from the Lambda runtime
    HEADERS="$(mktemp)"
    EVENT_DATA=$(curl -v -sS -LD "$HEADERS" -X GET "http://${AWS_LAMBDA_RUNTIME_API}/2018-06-01/runtime/invocation/next")
    INVOCATION_ID=$(grep -Fi Lambda-Runtime-Aws-Request-Id "$HEADERS" | tr -d '[:space:]' | cut -d: -f2)

    # Execute the COBOL function 
    RESPONSE=$(echo $EVENT_DATA | cobcrun $(echo $_HANDLER | cut -d. -f1))

    # Send the response to Lambda runtime
    curl -v -sS -X POST "http://${AWS_LAMBDA_RUNTIME_API}/2018-06-01/runtime/invocation/$INVOCATION_ID/response" -d "$RESPONSE"
done
